## docker-compose Bareos Director/Storage/Client/webUI and PostgreSQL Database based on Ubuntu
version: '3'
services:
  bareos-dir:
    image: barcus/bareos-director:20-ubuntu-pgsql #20-ubuntu-pgsql director-pgsql based on ubuntu
    volumes:
      - /opt/bareos/config/director:/etc/bareos
      - /opt/bareos/data/director:/var/lib/bareos #required for MyCatalog backup
    environment:
      - DB_INIT=false #should be 'true' if bareos db does not exist
      - DB_UPDATE=false
      - DB_HOST=bareos-db
      - DB_PORT=5432
      - DB_NAME=bareos
      - DB_USER=${DB_USER} # defined in .env file
      - DB_PASSWORD=${DB_PASSWORD} # defined in .env file
      - DB_ADMIN_USER=${DB_ADMIN_USER} # defined in .env file
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD} # defined in .env file
      - BAREOS_FD_HOST=bareos-fd
      - BAREOS_FD_PASSWORD=${BAREOS_FD_PASSWORD} # defined in .env file
      - BAREOS_SD_HOST=bareos-sd
      - BAREOS_SD_PASSWORD=${BAREOS_SD_PASSWORD} # defined in .env file
      - BAREOS_WEBUI_PASSWORD=${BAREOS_WEBUI_PASSWORD} # defined in .env file
      - SMTP_HOST=smtpd #SMTP_HOST is the name of smtp container
      - SENDER_MAIL=netmon@heinrichvz@unifiedsupport.co.za #optional
      - ADMIN_MAIL=heinrichvz@unifiedsupport.co.za # Change me!
      # Optional you can get backup notification via Slack or Telegram
      - WEBHOOK_NOTIFICATION=false # true or false if set to true email notification gets disabled
      - WEBHOOK_TYPE=slack # choose slack or telegram
      - WEBHOOK_URL= # set the slack or telegram URL
      - WEBHOOK_CHAT_ID= # for telegram only set the <chat_id>
    depends_on:
      - bareos-db

  bareos-sd:
    image: barcus/bareos-storage:20-ubuntu
    ports:
      - 9103:9103
    volumes:
      - /opt/bareos/config/storage:/etc/bareos
      - /opt/bareos/data/storage:/var/lib/bareos/storage
    environment:
      - BAREOS_SD_PASSWORD=${BAREOS_SD_PASSWORD} # defined in .env file

  bareos-fd:
    image: barcus/bareos-client:20-ubuntu
    volumes:
      - /opt/bareos/config/client:/etc/bareos
      - /opt/bareos/data/director:/var/lib/bareos-director #required for MyCatalog backup
    environment:
      - BAREOS_FD_PASSWORD=${BAREOS_FD_PASSWORD} # defined in .env file
      - FORCE_ROOT=false
      #- PUID=1500 # force bareos user ID
      #- PGID=1500 # force bareos group ID
  bareos-webui:
    image: barcus/bareos-webui:20-ubuntu
    ports:
      - 8080:80
    environment:
      - BAREOS_DIR_HOST=bareos-dir
      - SERVER_STATS=yes #optional enable apache server statistics
    volumes:
      - /opt/bareos/config/webui:/etc/bareos-webui

  bareos-db:
    image: postgres:12
    volumes:
      - /opt/bareos/pgsql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_ADMIN_USER} # defined in .env file
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD} # defined in .env file
      - POSTGRES_INITDB_ARGS=--encoding=SQL_ASCII

  bareos-api:
    image: barcus/bareos-api:21
    ports:
    - 8000:8000
    environment:
    - BAREOS_DIR_HOST=bareos-dir

  smtpd:
    image: namshi/smtp